- name: Install and configure knot-resolver and nginx for DNS + DoH
  become: true
  hosts: dns
  roles:
    - packages_dns
    - config_knot-resolver
    # - node-exporter
    - config_nginx
    - config_dns_certs
    - verify
