- name: Install and configure knot-resolver for DNS + DoT and nginx for DoH
  become: true
  hosts: dns
  roles:
    - packages_dns
    - config_dns_certs
    - config_knot-resolver
    # - node-exporter
    - config_nginx
    - verify
