
- name: Update netplan and manage users
  hosts: all
  become: true

  vars_prompt:
    - name: host_octet
      prompt: "Enter the last octet for the host IP (e.g., 42 for 192.168.1.42)"
      private: false

  roles:
    - config_netplan
    - create-users
    - config_openssh-server
