- name: Harden SSH configuration
  hosts: all
  become: yes

  tasks:
    - name: Ensure PasswordAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Ensure PermitRootLogin is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
