- name: Copy TLS pubkey for dns.disobey.net
  ansible.builtin.copy:
    src: /opt/certs/cert.pem
    dest: /opt/dns/cert.pem
    owner: root
    group: root
    mode: '0640'

- name: Copy TLS privkey for dns.disobey.net
  ansible.builtin.copy:
    src: /opt/certs/key.pem
    dest: /opt/dns/key.pem
    owner: root
    group: root
    mode: '0640'
