- name: Ensure PasswordAuthentication is disabled
  lineinansible.builtin.file:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: true

- name: Ensure PermitRootLogin is disabled
  lineinansible.builtin.file:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: true

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
