- name: Generate netplan config with dynamic IP
  ansible.builtin.copy:
    dest: /etc/netplan/01-static.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          ens18:
            dhcp4: false
            dhcp6: false
            accept-ra: false
            addresses:
              - 23.129.64.{{ host_octet }}/24
              - 2620:18c:0:192::33:{{ host_octet }}/64
            nameservers:
              addresses:
                - 1.1.1.1
                - 1.0.0.1
                - 2606:4700:4700::1111
                - 2606:4700:4700::1001
              search: []

            routes:
              - to: ::/0
                via: fe80::4a8f:5aff:fed5:258a
                on-link: true
                metric: 10
                from: 2620:18c:0:192::33:{{ host_octet }}
              - to: 0.0.0.0/0
                via: 23.129.64.1
                on-link: true
                metric: 100
  notify: Apply netplan